### ISSUE TITLE
{Feature request} Expansion to react-native

### ISSUE THREAD

**Issue by mikhaildmitrienko** [Seb-Park/Example-Flutter-Star-Wars#1]
Hi my name is Mikhail and I am new to this project. I was just wondering whether the repo's maintainers would be interested in including resources to introduce new students to react-native in addition to flutter. I would be happy to help out.

-Mikhail

P.S. I am a long time fan of Seb-Park, his work on the revolutionary game _Vector Funk_ is what inspired me to become the person I am today.

**Comment by Seb-Park** [comment]
Hi Mikhail,

We'd be happy to let you contribute some react native examples as well. Contribute as you see fit! I'm glad you love the game.
